apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DB_SECRET_NAME
              value: {{ .Values.backend.env.dbSecretName }}
            - name: AWS_REGION
              value: {{ .Values.global.awsRegion }}
            - name: SQL_ECHO
              value: {{ .Values.backend.env.sqlEcho }}
            - name: ALLOWED_ORIGINS
              value: {{ .Values.backend.env.allowedOrigins }}
            - name: APP_VERSION
              value: {{ .Values.backend.env.appVersion }}
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.backend.startupProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.backend.startupProbe.failureThreshold }}