apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.env.dbSecretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.namespace.name }}
type: Opaque
stringData:
  username: {{ .Values.backend.env.dbUsername }}
  password: {{ .Values.backend.env.dbPassword }}
  host: {{ .Values.backend.env.dbHost }}
  port: {{ .Values.backend.env.dbPort | quote }}
  dbname: {{ .Values.backend.env.dbName }}